//! Lists every JavaScript file the web app ships (the built site in target/site) and fails on anything that is not
//! generated by the Rust toolchain: only the wasm-bindgen loader for the app's own wasm module is allowed, and a
//! `snippets/` directory (JavaScript pasted into Rust crates) fails.

use std::path::Path;

use anyhow::{Result, bail};

pub fn check(root: &Path) -> Result<()> {
    let site = root.join("target/site");
    if !site.exists() {
        println!("shipped-js: no built site yet (target/site); nothing ships");
        return Ok(());
    }
    let mut problems = Vec::new();
    let mut count = 0usize;
    walk(&site, &mut |path| {
        let rel = path.strip_prefix(&site).unwrap_or(path).to_string_lossy().into_owned();
        if rel.split('/').any(|part| part == "snippets") {
            problems.push(format!("{rel}: JavaScript snippet from a crate"));
        }
        if rel.ends_with(".js") || rel.ends_with(".mjs") {
            count += 1;
            let size = std::fs::metadata(path).map(|m| m.len()).unwrap_or(0);
            let generated = rel.starts_with("pkg/") && rel.matches('/').count() == 1;
            println!(
                "shipped-js: {rel} ({size} bytes) {}",
                if generated {
                    "generated by wasm-bindgen"
                } else {
                    "NOT ALLOWED"
                }
            );
            if !generated {
                problems.push(format!("{rel}: not generated by the Rust toolchain"));
            }
        }
    })?;
    println!("shipped-js: {count} JavaScript file(s)");
    if problems.is_empty() {
        Ok(())
    } else {
        for p in &problems {
            eprintln!("shipped-js: {p}");
        }
        bail!("{} shipped JavaScript problem(s)", problems.len())
    }
}

fn walk(dir: &Path, f: &mut dyn FnMut(&Path)) -> Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            walk(&path, f)?;
        } else {
            f(&path);
        }
    }
    Ok(())
}
